using DomainSmith.Abstraction.Common;
using DomainSmith.Abstraction.Core.Primitives;

namespace DomainSmith.Entity.Examples.Entities;

public record OwnerId(Guid Value) : EntityIdRecord<Guid>(Value);

public record Address(string Street, string City, string State, string ZipCode);

[Entity(typeof(OwnerId))]
public partial class Owner
{
    public string FirstName { get; private set; }
    public string LastName { get; private set; }
    public string Email { get; private set; }
    public Address? Address { get; private set; }
    [ExcludeFromGeneration] public bool IsEnabled { get; private set; }
    [AutoGenerated] public DateTime? ModifiedAt { get; private set; }
    [AutoGenerated] public DateTime CreatedAt { get; private set; }
}