using DomainSmith.Abstraction.Common;
using DomainSmith.Abstraction.Core.Primitives;
using DomainSmith.Abstraction.Core.Result;

namespace DomainSmith.Entity.Examples.Entities;

[Entity(typeof(OwnerId))]
public partial class Owner
{
    public string FirstName { get; private set; }
    public string LastName { get; private set; }
    public string Email { get; private set; }
    public Address? Address { get; private set; }
    [ExcludeFromGeneration] public bool IsEnabled { get; private set; }
    [AutoGenerated] public DateTime? ModifiedAt { get; private set; }
    [AutoGenerated] public DateTime CreatedAt { get; private set; }

    public Result Activate()
    {
        IsEnabled = true;
        ModifiedAt = DateTime.Now;
        return Result.Success();
    }

    public Result Deactivate()
    {
        IsEnabled = false;
        ModifiedAt = DateTime.Now;
        return Result.Success();
    }

    partial void CreateCreatedAt() => CreatedAt = DateTime.Now;
    partial void UpdateCreatedAt() => ModifiedAt = DateTime.Now;
    partial void UpdateModifiedAt() => ModifiedAt = DateTime.Now;
}

public record OwnerId(Guid Value) : EntityIdRecord<Guid>(Value);

public record Address(string Street, string City, string State, string ZipCode);