using DomainSmith.Abstraction.Common.Models;
using DomainSmith.Entity.Generators;
using FluentAssertions;

namespace DomainSmith.Entity.Tests.Generators;

public sealed class EntityBuilderTests
{
    [Fact]
    public void Build_WithTwoProperties_ShouldGenerateClassWithCtorCreateUpdateHooks()
    {
        // Arrange
        var builder = new EntityBuilder();
        builder.SetUsings(["using System;"]);
        builder.SetNamespace("TestNamespace");
        builder.SetClassName("User");
        builder.SetTypeAgr("Guid");
        builder.SetIdValue("Guid.NewGuid()");
        builder.SetProperties([
            CreatePropertyInfo("string", "Name", false),
            CreatePropertyInfo("int", "Age", false)
        ]);
        builder.SetIsResultPattern(false);

        // Act
        var output = builder.Build();

        // Assert
        output.Should().NotBeNullOrWhiteSpace();
        output.Should().Contain("// <auto-generated/>");
        output.Should().Contain("namespace TestNamespace;");
        output.Should().Contain("partial class User : Entity<Guid>");
        output.Should().Contain("private User(Guid id, string name, int age) : base(id)");
        output.Should().Contain("Name = name;");
        output.Should().Contain("Age = age;");
        output.Should().Contain("internal static User? Create(string name, int age)");
        output.Should().Contain("bool canCreate = true;");
        output.Should().Contain("OnCreatingAuto(ref name, ref age, ref canCreate);");
        output.Should().Contain("OnCreating(ref name, ref age, ref canCreate);");
        output.Should().Contain("var result = new User(Guid.NewGuid(), name, age);");
        output.Should().Contain("OnCreated(result, ref canCreate);");
        output.Should().Contain("if(!canCreate) return null;");
        output.Should().Contain("return result;");
        output.Should().Contain("internal void Update(string name, int age)");
        output.Should().Contain("bool canUpdate = true;");
        output.Should().Contain("OnUpdatingAuto(ref name, ref age, ref canUpdate);");
        output.Should().Contain("OnUpdating(ref name, ref age, ref canUpdate);");
        output.Should().Contain("var tmpName = Name;");
        output.Should().Contain("var tmpAge = Age;");
        output.Should().Contain("Name = name;");
        output.Should().Contain("Age = age;");
        output.Should().Contain("OnUpdated(ref canUpdate);");
        output.Should().Contain("if(!canUpdate)");
        output.Should().Contain("Name = tmpName;");
        output.Should().Contain("Age = tmpAge;");
        output.Should().Contain("static partial void OnCreatingName(ref string name, ref bool canCreate);");
        output.Should().Contain("static partial void OnCreatingAge(ref int age, ref bool canCreate);");
        output.Should().Contain("partial void OnUpdatingName(ref string name, ref bool canUpdate);");
        output.Should().Contain("partial void OnUpdatingAge(ref int age, ref bool canUpdate);");
        output.Should().Contain("OnCreatingName(ref name, ref canCreate);");
        output.Should().Contain("OnCreatingAge(ref age, ref canCreate);");
        output.Should().Contain("OnUpdatingName(ref name, ref canUpdate);");
        output.Should().Contain("OnUpdatingAge(ref age, ref canUpdate);");

        builder.Clear();
    }

    [Fact]
    public void Build_WithAutoGeneratedProperty_ShouldIncludeCreateAndUpdateAutoMethodsCalls()
    {
        // Arrange
        var builder = new EntityBuilder();
        builder.SetUsings(["using System;"]);
        builder.SetNamespace("AutoNamespace");
        builder.SetClassName("Order");
        builder.SetTypeAgr("int");
        builder.SetIdValue("0");
        builder.SetProperties([
            CreatePropertyInfo("decimal", "Total", false),
            CreatePropertyInfo("DateTime", "CreatedAt", true)
        ]);
        builder.SetIsResultPattern(false);

        // Act
        var output = builder.Build();

        // Assert
        output.Should().NotBeNullOrWhiteSpace();
        output.Should().Contain("namespace AutoNamespace;");
        output.Should().Contain("partial class Order : Entity<int>");
        output.Should().Contain("private Order(int id, decimal total) : base(id)");
        output.Should().Contain("Total = total;");
        output.Should().Contain("internal static Order? Create(decimal total)");
        output.Should().Contain("var result = new Order(0, total);");
        output.Should().Contain("result.CreateCreatedAt();");
        output.Should().Contain("partial void CreateCreatedAt();");
        output.Should().Contain("internal void Update(decimal total)");
        output.Should().Contain("UpdateCreatedAt();");
        output.Should().Contain("partial void UpdateCreatedAt();");

        builder.Clear();
    }

    [Fact]
    public void Build_WithTwoPropertiesAndResultPattern_ShouldGenerateClassWithCtorCreateUpdateHooks()
    {
        // Arrange
        var builder = new EntityBuilder();
        builder.SetUsings(["using System;"]);
        builder.SetNamespace("TestNamespace");
        builder.SetClassName("User");
        builder.SetTypeAgr("Guid");
        builder.SetIdValue("Guid.NewGuid()");
        builder.SetProperties([
            CreatePropertyInfo("string", "Name", false),
            CreatePropertyInfo("int", "Age", false)
        ]);
        builder.SetIsResultPattern(true);

        // Act
        var output = builder.Build();

        // Assert
        output.Should().NotBeNullOrWhiteSpace();
        output.Should().Contain("// <auto-generated/>");
        output.Should().Contain("using DomainSmith.Abstraction.Core.Result;");
        output.Should().Contain("namespace TestNamespace;");
        output.Should().Contain("partial class User : Entity<Guid>");
        output.Should().Contain("private User(Guid id, string name, int age) : base(id)");
        output.Should().Contain("Name = name;");
        output.Should().Contain("Age = age;");
        output.Should().Contain("internal static Result<User> Create(string name, int age)");
        output.Should().Contain("bool canCreate = true;");
        output.Should().Contain("Error error = Error.None;");
        output.Should().Contain("OnCreatingAuto(ref name, ref age, ref canCreate, ref error);");
        output.Should().Contain("OnCreating(ref name, ref age, ref canCreate, ref error);");
        output.Should().Contain("var result = new User(Guid.NewGuid(), name, age);");
        output.Should().Contain("OnCreated(result, ref canCreate, ref error);");
        output.Should().Contain("if(!canCreate) return Result.Failure<User>(error);");
        output.Should().Contain("return Result.Success(result);");
        output.Should().Contain("internal Result<bool> Update(string name, int age)");
        output.Should().Contain("bool canUpdate = true;");
        output.Should().Contain("Error error = Error.None;");
        output.Should().Contain("OnUpdatingAuto(ref name, ref age, ref canUpdate, ref error);");
        output.Should().Contain("OnUpdating(ref name, ref age, ref canUpdate, ref error);");
        output.Should().Contain("var tmpName = Name;");
        output.Should().Contain("var tmpAge = Age;");
        output.Should().Contain("Name = name;");
        output.Should().Contain("Age = age;");
        output.Should().Contain("OnUpdated(ref canUpdate, ref error);");
        output.Should().Contain("if(!canUpdate)");
        output.Should().Contain("Name = tmpName;");
        output.Should().Contain("Age = tmpAge;");
        output.Should().Contain("return Result.Failure<bool>(error);");
        output.Should().Contain("return Result.Success(true);");
        output.Should()
            .Contain(
                "private static void OnCreatingAuto(ref string name, ref int age, ref bool canCreate, ref Error error)");
        output.Should()
            .Contain("private void OnUpdatingAuto(ref string name, ref int age, ref bool canUpdate, ref Error error)");
        output.Should()
            .Contain(
                "static partial void OnCreating(ref string name, ref int age, ref bool canCreate, ref Error error);");
        output.Should().Contain("static partial void OnCreated(User result, ref bool canCreate, ref Error error);");
        output.Should()
            .Contain("partial void OnUpdating(ref string name, ref int age, ref bool canUpdate, ref Error error);");
        output.Should().Contain("partial void OnUpdated(ref bool canUpdate, ref Error error);");
        output.Should()
            .Contain("static partial void OnCreatingName(ref string name, ref bool canCreate, ref Error error);");
        output.Should().Contain("static partial void OnCreatingAge(ref int age, ref bool canCreate, ref Error error);");
        output.Should().Contain("partial void OnUpdatingName(ref string name, ref bool canUpdate, ref Error error);");
        output.Should().Contain("partial void OnUpdatingAge(ref int age, ref bool canUpdate, ref Error error);");
        output.Should().Contain("OnCreatingName(ref name, ref canCreate, ref error);");
        output.Should().Contain("OnCreatingAge(ref age, ref canCreate, ref error);");
        output.Should().Contain("OnUpdatingName(ref name, ref canUpdate, ref error);");
        output.Should().Contain("OnUpdatingAge(ref age, ref canUpdate, ref error);");

        builder.Clear();
    }

    [Fact]
    public void Build_WithAutoGeneratedPropertyAndResultPattern_ShouldIncludeCreateAndUpdateAutoMethodsCalls()
    {
        // Arrange
        var builder = new EntityBuilder();
        builder.SetUsings(["using System;"]);
        builder.SetNamespace("AutoNamespace");
        builder.SetClassName("Order");
        builder.SetTypeAgr("int");
        builder.SetIdValue("0");
        builder.SetProperties([
            CreatePropertyInfo("decimal", "Total", false),
            CreatePropertyInfo("DateTime", "CreatedAt", true)
        ]);
        builder.SetIsResultPattern(true);

        // Act
        var output = builder.Build();

        // Assert
        output.Should().NotBeNullOrWhiteSpace();
        output.Should().Contain("namespace AutoNamespace;");
        output.Should().Contain("partial class Order : Entity<int>");
        output.Should().Contain("private Order(int id, decimal total) : base(id)");
        output.Should().Contain("Total = total;");
        // Create remains Result<Order> when Result Pattern is enabled (default)
        output.Should().Contain("internal static Result<Order> Create(decimal total)");
        output.Should().Contain("var result = new Order(0, total);");
        output.Should().Contain("result.CreateCreatedAt();");
        output.Should().Contain("partial void CreateCreatedAt();");
        // Update returns Result<bool> with Result Pattern
        output.Should().Contain("internal Result<bool> Update(decimal total)");
        output.Should().Contain("UpdateCreatedAt();");
        output.Should().Contain("partial void UpdateCreatedAt();");

        builder.Clear();
    }

    [Fact]
    public void Build_WithMissingInputs_ShouldReturnEmptyString()
    {
        // Arrange
        var builder = new EntityBuilder();

        // Act
        var output = builder.Build();

        // Assert
        output.Should().BeEmpty();
    }

    private static PropertyInfo CreatePropertyInfo(string type, string name, bool autoGenerated)
        => new(type, name, autoGenerated);
}