using System.Reflection;
using DomainSmith.Entity.Generators;
using FluentAssertions;

namespace DomainSmith.Entity.Tests.Generators;

public sealed class EntityBuilderTests
{
    private static object CreatePropertyInfo(string type, string name, bool autoGenerated)
    {
        var nested =
            typeof(EntityGenerator).GetNestedType("PropertyInfo", BindingFlags.Public | BindingFlags.NonPublic);
        nested.Should().NotBeNull("PropertyInfo nested type must exist");

        var instance = Activator.CreateInstance(
            nested,
            BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic,
            binder: null,
            args: [type, name, autoGenerated],
            culture: null);

        instance.Should().NotBeNull("PropertyInfo instance should be creatable via reflection");
        return instance;
    }

    [Fact]
    public void Build_WithTwoProperties_ShouldGenerateClassWithCtorCreateUpdateHooks()
    {
        // Arrange
        var builder = new EntityBuilder();
        builder.SetUsings(["using System;"]);
        builder.SetNamespace("TestNamespace");
        builder.SetClassName("User");
        builder.SetTypeAgr("Guid");
        builder.SetIdValue("Guid.NewGuid()");
        builder.SetProperties([
            (EntityGenerator.PropertyInfo)CreatePropertyInfo("string", "Name", false),
            (EntityGenerator.PropertyInfo)CreatePropertyInfo("int", "Age", false)
        ]);

        // Act
        var output = builder.Build();

        // Assert
        output.Should().NotBeNullOrWhiteSpace();
        output.Should().Contain("// <auto-generated/>");
        output.Should().Contain("namespace TestNamespace;");
        output.Should().Contain("partial class User : Entity<Guid>");
        output.Should().Contain("private User(Guid id, string name, int age) : base(id)");
        output.Should().Contain("Name = name;");
        output.Should().Contain("Age = age;");
        output.Should().Contain("internal static User? Create(string name, int age)");
        output.Should().Contain("bool canCreate = true;");
        output.Should().Contain("OnCreatingAuto(ref name, ref age, ref canCreate);");
        output.Should().Contain("OnCreating(ref name, ref age, ref canCreate);");
        output.Should().Contain("var result = new User(Guid.NewGuid(), name, age);");
        output.Should().Contain("OnCreated(result, ref canCreate);");
        output.Should().Contain("if(!canCreate) return null;");
        output.Should().Contain("return result;");
        output.Should().Contain("internal void Update(string name, int age)");
        output.Should().Contain("bool canUpdate = true;");
        output.Should().Contain("OnUpdatingAuto(ref name, ref age, ref canUpdate);");
        output.Should().Contain("OnUpdating(ref name, ref age, ref canUpdate);");
        output.Should().Contain("var tmpName = Name;");
        output.Should().Contain("var tmpAge = Age;");
        output.Should().Contain("Name = name;");
        output.Should().Contain("Age = age;");
        output.Should().Contain("OnUpdated(ref canUpdate);");
        output.Should().Contain("if(!canUpdate)");
        output.Should().Contain("Name = tmpName;");
        output.Should().Contain("Age = tmpAge;");
        output.Should().Contain("static partial void OnCreatingName(ref string name, ref bool canCreate);");
        output.Should().Contain("static partial void OnCreatingAge(ref int age, ref bool canCreate);");
        output.Should().Contain("partial void OnUpdatingName(ref string name, ref bool canUpdate);");
        output.Should().Contain("partial void OnUpdatingAge(ref int age, ref bool canUpdate);");
        output.Should().Contain("OnCreatingName(ref name, ref canCreate);");
        output.Should().Contain("OnCreatingAge(ref age, ref canCreate);");
        output.Should().Contain("OnUpdatingName(ref name, ref canUpdate);");
        output.Should().Contain("OnUpdatingAge(ref age, ref canUpdate);");

        builder.Clear();
    }

    [Fact]
    public void Build_WithAutoGeneratedProperty_ShouldIncludeCreateAndUpdateAutoMethodsCalls()
    {
        // Arrange
        var builder = new EntityBuilder();
        builder.SetUsings(["using System;"]);
        builder.SetNamespace("AutoNamespace");
        builder.SetClassName("Order");
        builder.SetTypeAgr("int");
        builder.SetIdValue("0");
        builder.SetProperties([
            (EntityGenerator.PropertyInfo)CreatePropertyInfo("decimal", "Total", false),
            (EntityGenerator.PropertyInfo)CreatePropertyInfo("DateTime", "CreatedAt", true)
        ]);

        // Act
        var output = builder.Build();

        // Assert
        output.Should().NotBeNullOrWhiteSpace();
        output.Should().Contain("namespace AutoNamespace;");
        output.Should().Contain("partial class Order : Entity<int>");
        output.Should().Contain("private Order(int id, decimal total) : base(id)");
        output.Should().Contain("Total = total;");
        output.Should().Contain("internal static Order? Create(decimal total)");
        output.Should().Contain("var result = new Order(0, total);");
        output.Should().Contain("result.CreateCreatedAt();");
        output.Should().Contain("partial void CreateCreatedAt();");
        output.Should().Contain("internal void Update(decimal total)");
        output.Should().Contain("UpdateCreatedAt();");
        output.Should().Contain("partial void UpdateCreatedAt();");

        builder.Clear();
    }

    [Fact]
    public void Build_WithMissingInputs_ShouldReturnEmptyString()
    {
        // Arrange
        var builder = new EntityBuilder();

        // Act
        var output = builder.Build();

        // Assert
        output.Should().BeEmpty();
    }
}