using DomainSmith.ValueObject.Generators;
using FluentAssertions;

namespace DomainSmith.ValueObject.Tests.Generators;

public sealed class ValueObjectBuilderTests
{
    [Fact]
    public void Build_WithTwoProperties_ShouldGenerateRecordWithCtorCreateAndHooks()
    {
        // Arrange
        var builder = new ValueObjectBuilder();
        builder.SetUsings(["using System;"]);
        builder.SetNamespace("TestNamespace");
        builder.SetClassName("Money");
        builder.SetProperties([
            ("decimal", "Amount"),
            ("string", "Currency")
        ]);

        // Act
        var output = builder.Build();

        // Assert
        output.Should().NotBeNullOrWhiteSpace();
        output.Should().Contain("// <auto-generated/>");
        output.Should().Contain("namespace TestNamespace;");
        output.Should().Contain("partial record Money");
        output.Should().Contain("private Money(decimal amount, string currency)");
        output.Should().Contain("Amount = amount;");
        output.Should().Contain("Currency = currency;");
        output.Should().Contain("public static Money? Create(decimal amount, string currency)");
        output.Should().Contain("bool canCreate = true;");
        output.Should().Contain("OnCreating(ref amount, ref currency, ref canCreate);");
        output.Should().Contain("var result = new Money(amount, currency);");
        output.Should().Contain("OnCreated(result, ref canCreate);");
        output.Should().Contain("if (!canCreate) return null;");
        output.Should().Contain("return result;");
        output.Should()
            .Contain("static partial void OnCreating(ref decimal amount, ref string currency, ref bool canCreate);");
        output.Should().Contain("static partial void OnCreated(Money instance, ref bool canCreate);");

        builder.Clear();
    }

    [Fact]
    public void Build_WithSingleProperty_ShouldGenerateCorrectParametersAndAssignments()
    {
        // Arrange
        var builder = new ValueObjectBuilder();
        builder.SetUsings(["using System;"]);
        builder.SetNamespace("AnotherNamespace");
        builder.SetClassName("Temperature");
        builder.SetProperties([("double", "Celsius")]);

        // Act
        var output = builder.Build();

        // Assert
        output.Should().NotBeNullOrWhiteSpace();
        output.Should().Contain("namespace AnotherNamespace;");
        output.Should().Contain("partial record Temperature");
        output.Should().Contain("private Temperature(double celsius)");
        output.Should().Contain("Celsius = celsius;");
        output.Should().Contain("public static Temperature? Create(double celsius)");
        output.Should().Contain("OnCreating(ref celsius, ref canCreate);");
        output.Should().Contain("var result = new Temperature(celsius);");
        output.Should().Contain("OnCreated(result, ref canCreate);");
        output.Should().Contain("static partial void OnCreating(ref double celsius, ref bool canCreate);");
        output.Should().Contain("static partial void OnCreated(Temperature instance, ref bool canCreate);");

        builder.Clear();
    }

    [Fact]
    public void Build_WithMissingInputs_ShouldReturnEmptyString()
    {
        // Arrange
        var builder = new ValueObjectBuilder();

        // Act
        var output = builder.Build();

        // Assert
        output.Should().BeEmpty();
    }
}