using System.Text;
using DomainSmith.Abstraction.Extensions;
using DomainSmith.Abstraction.Generators;

namespace DomainSmith.Repository.Generators;

internal sealed class RepositoryBuilder : BaseBuilder
{
    private readonly StringBuilder _idType = new();

    internal void SetIdType(string idType)
    {
        _idType.Clear();
        _idType.Append(idType);
    }

    protected override string BuildSource()
    {
        ApplyConditionalUsings();

        var repositoryInterfaceName = $"I{ClassName}Repository";

        return $$"""
                 // <auto-generated/>
                 {{Usings}}

                 {{Namespace}}

                 public interface {{repositoryInterfaceName}}
                 {
                     Task<DomainSmith.Abstraction.Core.Maybe.Maybe<{{ClassName}}>> GetByIdAsync({{_idType}} id, CancellationToken cancellationToken = default);

                     Task<IReadOnlyCollection<{{ClassName}}>> GetAllAsync({{_idType}} id, CancellationToken cancellationToken = default);

                     Task AddAsync({{ClassName}} {{(ClassName.ToString().ToCamel())}}, CancellationToken cancellationToken = default);

                     void Remove({{ClassName}} id);
                 }
                 """;
    }

    private void ApplyConditionalUsings()
    {
        if (!Usings.ToString().Contains("using DomainSmith.Abstraction.Core.Maybe;"))
            Usings.Append("\nusing DomainSmith.Abstraction.Core.Maybe;");
    }


    protected override bool IsEmpty() =>
        Usings.Length == 0 &&
        Namespace.Length == 0 &&
        ClassName.Length == 0 &&
        _idType.Length == 0;

    internal override void Clear()
    {
        base.Clear();
        _idType.Clear();
    }
}