using DomainSmith.Abstraction.Common;
using DomainSmith.Abstraction.Generators;
using DomainSmith.Abstraction.Helpers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DomainSmith.AggregateRoot.Generators;

[Generator]
internal sealed class
    AggregateRootGenerator : BaseGenerator<ClassDeclarationSyntax, AggregateRootGenerator.ClassToAugment>
{
    protected override string AttributeFullName => typeof(AggregateRootAttribute).FullName!;

    protected override string GenerateSource(ClassToAugment info)
    {
        var builder = new AggregateRootBuilder();

        builder.SetUsings(info.Usings);
        builder.SetNamespace(info.Namespace);
        builder.SetClassName(info.Name);
        builder.SetTypeAgr(info.TypeArg);
        builder.SetIdValue(GetIdValueExpression(info));
        builder.SetExtensionName(info.Name);
        builder.SetProperties(info.Properties);

        var source = builder.Build();
        builder.Clear();

        return source;
    }

    protected override ClassToAugment? CreateInfo(ClassDeclarationSyntax classSyntax, GeneratorSyntaxContext context)
    {
        var name = classSyntax.Identifier.Text;
        var ns = classSyntax.FirstAncestorOrSelf<NamespaceDeclarationSyntax>()?.Name.ToString()
                 ?? classSyntax.FirstAncestorOrSelf<FileScopedNamespaceDeclarationSyntax>()?.Name.ToString();

        var usings = classSyntax
            .FirstAncestorOrSelf<CompilationUnitSyntax>()?
            .DescendantNodesAndSelf()
            .OfType<UsingDirectiveSyntax>()
            .Select(x => $"using {x.Name};")
            .Distinct()
            .ToList() ?? [];

        usings.Add("using DomainSmith.Abstraction.Core.Primitives;");


        var attributeSyntaxes = classSyntax.AttributeLists
            .SelectMany(list => list.Attributes)
            .Select(attr => new
            {
                attr,
                symbol = context.SemanticModel.GetSymbolInfo(attr).Symbol as IMethodSymbol
            })
            .Where(x => x.symbol?.ContainingType.ToDisplayString() == AttributeFullName)
            .Select(x => x.attr);

        var typeArg = "int";
        INamedTypeSymbol? idTypeSymbol = null;
        foreach (var attr in attributeSyntaxes)
        {
            if (!(attr.ArgumentList?.Arguments.Count > 0)
                || attr.ArgumentList.Arguments[0].Expression is not TypeOfExpressionSyntax typeOfExpr)
                continue;

            typeArg = typeOfExpr.Type.ToString();
            idTypeSymbol = context.SemanticModel.GetTypeInfo(typeOfExpr.Type).Type as INamedTypeSymbol;
            break;
        }

        if (idTypeSymbol == null) return null;

        var isAggregateRootIdRecord = false;
        var isAggregateRootIdClass = false;
        string? idValueType = null;
        var idTypeFullName = idTypeSymbol.ToDisplayString();
        for (var baseType = idTypeSymbol.BaseType; baseType != null; baseType = baseType.BaseType)
        {
            var baseName = baseType.ConstructedFrom.ToDisplayString();
            if (baseName == "DomainSmith.Abstraction.Core.Primitives.EntityIdRecord<T>")
            {
                isAggregateRootIdRecord = true;
                idValueType = baseType.TypeArguments.FirstOrDefault()?.ToDisplayString();
                break;
            }

            if (baseName == "DomainSmith.Abstraction.Core.Primitives.EntityIdClass<T>")
            {
                isAggregateRootIdClass = true;
                idValueType = baseType.TypeArguments.FirstOrDefault()?.ToDisplayString();
                break;
            }
        }

        var properties = classSyntax.Members
            .OfType<PropertyDeclarationSyntax>()
            .Where(p =>
            {
                var symbol = context.SemanticModel.GetDeclaredSymbol(p);
                return symbol is not null &&
                       !symbol.GetAttributes().Any(a =>
                           a.AttributeClass?.ToDisplayString() == typeof(ExcludeFromGenerationAttribute).FullName!);
            })
            .Select(p =>
            {
                var symbol = context.SemanticModel.GetDeclaredSymbol(p);
                var isAutoGenerated = symbol?.GetAttributes().Any(a =>
                    a.AttributeClass?.ToDisplayString() == typeof(AutoGeneratedAttribute).FullName!) == true;
                return new PropertyInfo(
                    p.Type.ToString(),
                    p.Identifier.Text,
                    isAutoGenerated
                );
            })
            .ToList();

        return new ClassToAugment(
            name,
            typeArg,
            ns,
            usings,
            idTypeFullName,
            isAggregateRootIdRecord,
            isAggregateRootIdClass,
            idValueType,
            properties
        );
    }

    private static string GetIdValueExpression(ClassToAugment info)
    {
        var valueExpr = info.TypeArg.ToGeneratingExpression();

        if (valueExpr is not null)
            return valueExpr;

        if (info is { IsAggregateRootIdRecord: false, IsAggregateRootIdClass: false } ||
            string.IsNullOrEmpty(info.IdValueType))
            return "default";

        valueExpr = info.IdValueType.ToGeneratingExpression();

        return $"new {info.TypeArg}({valueExpr})";
    }

    public sealed class ClassToAugment(
        string name,
        string typeArg,
        string? ns,
        List<string> usings,
        string? idTypeFullName,
        bool isAggregateRootIdRecord,
        bool isAggregateRootIdClass,
        string? idValueType,
        List<PropertyInfo> properties)
    {
        public string Name { get; } = name;
        public string TypeArg { get; } = typeArg;
        public string? Namespace { get; } = ns;
        public List<string> Usings { get; } = usings;
        public string? IdTypeFullName { get; } = idTypeFullName;
        public bool IsAggregateRootIdRecord { get; } = isAggregateRootIdRecord;
        public bool IsAggregateRootIdClass { get; } = isAggregateRootIdClass;
        public string? IdValueType { get; } = idValueType;
        public List<PropertyInfo> Properties { get; } = properties;
    }

    public sealed class PropertyInfo(string type, string name, bool autoGenerated)
    {
        public string Type { get; } = type;
        public string Name { get; } = name;

        public bool AutoGenerated { get; set; } = autoGenerated;
    }
}