using System.Text;
using DomainSmith.Abstraction.Generators;

namespace DomainSmith.AggregateRoot.Generators;

internal sealed class AggregateRootBuilder : BaseBuilder
{
    private readonly StringBuilder _typeAgr = new();
    private readonly StringBuilder _idValue = new();
    private readonly StringBuilder _extensionName = new();
    private List<(string Type, string Name, bool AutoGenerated)> _properties = [];
    private bool _isResultPattern = true;
    private List<AggregateRootGenerator.EntityCollectionInfo> _entityCollections = [];

    internal void SetTypeAgr(string typeAgr)
    {
        _typeAgr.Clear();
        _typeAgr.Append(typeAgr);
    }

    internal void SetIdValue(string idValue)
    {
        _idValue.Clear();
        _idValue.Append(idValue);
    }

    internal void SetExtensionName(string className)
    {
        _extensionName.Clear();
        _extensionName.Append(className);
        _extensionName.Append("Extensions");
    }

    internal void SetProperties(List<AggregateRootGenerator.PropertyInfo> properties)
    {
        _properties = [.. properties.Select(p => (p.Type, p.Name, p.AutoGenerated))];
    }

    internal void SetIsResultPattern(bool isResultPattern)
    {
        _isResultPattern = isResultPattern;
    }

    internal void SetEntityCollections(List<AggregateRootGenerator.EntityCollectionInfo> entityCollections)
    {
        _entityCollections = entityCollections;
    }

    protected override string BuildSource()
    {
        const string resultStr = "result";
        var ctorParams = new List<string> { $"{_typeAgr} id" };
        var ctorAssignments = new List<string>();
        var createParams = new List<string>();
        var createArgs = new List<string> { _idValue.ToString() };
        var onCreatingParams = new List<string>();
        var onUpdatingParams = new List<string>();
        var onCreatingRefParams = new List<string>();
        var onUpdatingRefParams = new List<string>();
        var updateAssignments = new List<string>();
        var updateTmpVars = new List<string>();
        var updateRestore = new List<string>();
        var createAutoGeneratedProps = new List<string>();
        var createAutoGeneratedMethods = new List<string>();
        var updateAutoGeneratedProps = new List<string>();
        var updateAutoGeneratedMethods = new List<string>();

        var perCreateDecls = new List<string>();
        var perUpdateDecls = new List<string>();
        var perCreateInvocations = new List<string>();
        var perUpdateInvocations = new List<string>();

        foreach (var (type, name, autoGenerated) in _properties)
        {
            if (autoGenerated)
            {
                createAutoGeneratedProps.Add($"{resultStr}.Create{name}();");
                updateAutoGeneratedProps.Add($"Update{name}();");

                createAutoGeneratedMethods.Add($"partial void Create{name}();");
                updateAutoGeneratedMethods.Add($"partial void Update{name}();");

                continue;
            }

            var lower = name.ToLower();
            ctorParams.Add($"{type} {lower}");
            ctorAssignments.Add($"{name} = {lower};");
            createParams.Add($"{type} {lower}");
            createArgs.Add($"{lower}");
            onCreatingParams.Add($"ref {type} {lower}");
            onUpdatingParams.Add($"ref {type} {lower}");
            onCreatingRefParams.Add($"ref {lower}");
            onUpdatingRefParams.Add($"ref {lower}");
            updateTmpVars.Add($"var tmp{name} = {name};");
            updateAssignments.Add($"{name} = {lower};");
            updateRestore.Add($"{name} = tmp{name};");

            perCreateDecls.Add(
                $"static partial void OnCreating{name}(ref {type} {lower}, {(_isResultPattern ? "ref bool canCreate, ref Error error" : "ref bool canCreate")});");
            perUpdateDecls.Add(
                $"partial void OnUpdating{name}(ref {type} {lower}, {(_isResultPattern ? "ref bool canUpdate, ref Error error" : "ref bool canUpdate")});");

            perCreateInvocations.Add(
                $"OnCreating{name}(ref {lower}, {(_isResultPattern ? "ref canCreate, ref error" : "ref canCreate")});");
            perUpdateInvocations.Add(
                $"OnUpdating{name}(ref {lower}, {(_isResultPattern ? "ref canUpdate, ref error" : "ref canUpdate")});");
        }

        var ctorParamsStr = string.Join(", ", ctorParams);
        var ctorAssignmentsStr = string.Join("\n\t\t", ctorAssignments);
        var createParamsStr = string.Join(", ", createParams);
        var createArgsStr = string.Join(", ", createArgs);
        var onCreatingParamsStr = string.Join(", ", onCreatingParams);
        var onUpdatingParamsStr = string.Join(", ", onUpdatingParams);
        var onCreatingRefParamsStr = string.Join(", ", onCreatingRefParams);
        var onUpdatingRefParamsStr = string.Join(", ", onUpdatingRefParams);
        var updateTmpVarsStr = string.Join("\n\t\t", updateTmpVars);
        var updateAssignmentsStr = string.Join("\n\t\t", updateAssignments);
        var updateRestoreStr = string.Join("\n\t\t\t", updateRestore);
        var createAutoGeneratedPropsStr = string.Join("\n\t\t", createAutoGeneratedProps);
        var createAutoGeneratedMethodsStr = string.Join("\n\t", createAutoGeneratedMethods);
        var updateAutoGeneratedPropsStr = string.Join("\n\t\t", updateAutoGeneratedProps);
        var updateAutoGeneratedMethodsStr = string.Join("\n\t", updateAutoGeneratedMethods);

        var perCreateDeclsStr = string.Join("\n\t", perCreateDecls);
        var perUpdateDeclsStr = string.Join("\n\t", perUpdateDecls);
        var perCreateInvocationsStr = string.Join("\n\t\t", perCreateInvocations);
        var perUpdateInvocationsStr = string.Join("\n\t\t", perUpdateInvocations);

        var createResultType = _isResultPattern ? $"Result<{ClassName}>" : $"{ClassName}?";
        var createReturnSuccess = _isResultPattern ? $"return Result.Success({resultStr});" : $"return {resultStr};";
        var createFailReturn = _isResultPattern ? $"return Result.Failure<{ClassName}>(error);" : "return null;";
        var createRefDeclParams = _isResultPattern ? "ref bool canCreate, ref Error error" : "ref bool canCreate";
        var createRefParams = _isResultPattern ? "ref canCreate, ref error" : "ref canCreate";
        var createRefVars = _isResultPattern
            ? "bool canCreate = true;\n\t\tError error = Error.None;"
            : "bool canCreate = true;";

        var updateReturnType = _isResultPattern ? "Result<bool>" : "void";
        var updateReturnOnSuccess = _isResultPattern ? "return Result.Success(true);" : "return;";
        var updateReturnOnFailure = _isResultPattern ? "return Result.Failure<bool>(error);" : "return;";
        var updateRefDeclParams = _isResultPattern ? "ref bool canUpdate, ref Error error" : "ref bool canUpdate";
        var updateRefParams = _isResultPattern ? "ref canUpdate, ref error" : "ref canUpdate";
        var updateRefVars = _isResultPattern
            ? "bool canUpdate = true;\n\t\tError error = Error.None;"
            : "bool canUpdate = true;";

        if (_isResultPattern)
        {
            Usings.Append("\nusing DomainSmith.Abstraction.Core.Result;");
        }

        if (_entityCollections.Count > 0)
        {
            Usings.Append("\nusing System.Linq;");
            if (_isResultPattern)
            {
                Usings.Append("\nusing DomainSmith.Abstraction.Common;");
                Usings.Append("\nusing DomainSmith.Abstraction.Core.Result;");
            }
        }

        var entityCollectionsMembersStr = BuildEntityCollectionsMembers();

        return $$"""
                 // <auto-generated/>
                 {{Usings}}

                 {{Namespace}}

                 partial class {{ClassName}} : AggregateRoot<{{_typeAgr}}>
                 {
                     private {{ClassName}}({{ctorParamsStr}}) : base(id)
                     {
                         {{ctorAssignmentsStr}}
                     }

                     public static {{createResultType}} Create({{createParamsStr}})
                     {
                         {{createRefVars}}
                         OnCreatingAuto({{onCreatingRefParamsStr}}, {{createRefParams}});
                         OnCreating({{onCreatingRefParamsStr}}, {{createRefParams}});
                     
                         var {{resultStr}} = new {{ClassName}}({{createArgsStr}});
                                                  
                         OnCreated({{resultStr}}, {{createRefParams}});
                         if(!canCreate) {{createFailReturn}}

                         {{createAutoGeneratedPropsStr}}

                         {{createReturnSuccess}}
                     }
                     
                     public {{updateReturnType}} Update({{createParamsStr}})
                     {
                         {{updateRefVars}}
                         OnUpdatingAuto({{onUpdatingRefParamsStr}}, {{updateRefParams}});
                         OnUpdating({{onUpdatingRefParamsStr}}, {{updateRefParams}});
                         
                         {{updateTmpVarsStr}}
                         {{updateAssignmentsStr}}
                         
                         OnUpdated({{updateRefParams}});
                         if(!canUpdate)
                         {
                            {{updateRestoreStr}}
                            {{updateReturnOnFailure}}
                         }
                         {{updateAutoGeneratedPropsStr}}
                     
                         {{updateReturnOnSuccess}}
                     }

                     private static void OnCreatingAuto({{onCreatingParamsStr}}, {{createRefDeclParams}})
                     {
                         {{perCreateInvocationsStr}}
                     }

                     private void OnUpdatingAuto({{onUpdatingParamsStr}}, {{updateRefDeclParams}})
                     {
                         {{perUpdateInvocationsStr}}
                     }
                     
                     static partial void OnCreating({{onCreatingParamsStr}}, {{createRefDeclParams}});
                     static partial void OnCreated({{ClassName}} result, {{createRefDeclParams}});

                     partial void OnUpdating({{onUpdatingParamsStr}}, {{updateRefDeclParams}});
                     partial void OnUpdated({{updateRefDeclParams}});

                     {{createAutoGeneratedMethodsStr}}
                     {{updateAutoGeneratedMethodsStr}}

                     {{perCreateDeclsStr}}
                     {{perUpdateDeclsStr}}

                     {{entityCollectionsMembersStr}}
                 }                 
                 """;
    }

    private string BuildEntityCollectionsMembers()
    {
        if (_entityCollections.Count == 0)
            return string.Empty;

        var sb = new StringBuilder();

        foreach (var c in _entityCollections)
        {
            sb.AppendLine();

            if (c.GenerateProperty)
            {
                sb.AppendLine(
                    $"\tpublic IReadOnlyCollection<{c.ElementType}> {c.PropertyName} => {c.BackingFieldName};");
                sb.AppendLine();
            }

            var addName = $"AddNewElementTo{c.PropertyName}";
            var updateName = $"UpdateElementIn{c.PropertyName}";
            var deleteName = $"DeleteElementFrom{c.PropertyName}";

            var argsDecl = string.Join(", ", c.CtorArgs.Select(a => $"{a.Type} {a.Name}"));
            var argsCall = string.Join(", ", c.CtorArgs.Select(a => a.Name));

            if (_isResultPattern)
            {
                // Owner zwraca Result-y
                if (c.ElementIsResultPattern)
                {
                    // element też zwraca Result
                    sb.AppendLine($"\tpublic Result<{c.ElementType}> {addName}({argsDecl})");
                    sb.AppendLine("\t{");
                    sb.AppendLine($"\t\tvar result = {c.ElementType}.Create({argsCall});");
                    sb.AppendLine("\t\tif (result.IsFailure)");
                    sb.AppendLine("\t\t\treturn result;");
                    sb.AppendLine();
                    sb.AppendLine("\t\tvar entity = result.Value();");
                    sb.AppendLine($"\t\t{c.BackingFieldName}.Add(entity);");
                    sb.AppendLine();
                    sb.AppendLine("\t\treturn entity;");
                    sb.AppendLine("\t}");
                    sb.AppendLine();

                    sb.AppendLine($"\tpublic Result {updateName}({c.ElementIdType} id, {argsDecl})");
                    sb.AppendLine("\t{");
                    sb.AppendLine($"\t\tvar entity = {c.BackingFieldName}.FirstOrDefault(a => a.Id == id);");
                    sb.AppendLine("\t\tif (entity is null)");
                    sb.AppendLine(
                        $"\t\t\treturn Result.Failure(new Error(\"{ClassName}.{c.PropertyName}\", \"Not found\"));");
                    sb.AppendLine();
                    sb.AppendLine($"\t\tvar result = entity.Update({argsCall});");
                    sb.AppendLine();
                    sb.AppendLine("\t\treturn result;");
                    sb.AppendLine("\t}");
                    sb.AppendLine();
                }
                else
                {
                    // element ma [NoResultPattern]: Create -> T?, Update -> void
                    sb.AppendLine($"\tpublic Result<{c.ElementType}> {addName}({argsDecl})");
                    sb.AppendLine("\t{");
                    sb.AppendLine($"\t\tvar entity = {c.ElementType}.Create({argsCall});");
                    sb.AppendLine("\t\tif (entity is null)");
                    sb.AppendLine(
                        $"\t\t\treturn Result.Failure<{c.ElementType}>(new Error(\"{c.ElementType}.Create\", \"Creation failed\"));");
                    sb.AppendLine();
                    sb.AppendLine($"\t\t{c.BackingFieldName}.Add(entity);");
                    sb.AppendLine();
                    sb.AppendLine("\t\treturn entity;");
                    sb.AppendLine("\t}");
                    sb.AppendLine();

                    sb.AppendLine($"\tpublic Result {updateName}({c.ElementIdType} id, {argsDecl})");
                    sb.AppendLine("\t{");
                    sb.AppendLine($"\t\tvar entity = {c.BackingFieldName}.FirstOrDefault(a => a.Id == id);");
                    sb.AppendLine("\t\tif (entity is null)");
                    sb.AppendLine(
                        $"\t\t\treturn Result.Failure(new Error(\"{ClassName}.{c.PropertyName}\", \"Not found\"));");
                    sb.AppendLine();
                    sb.AppendLine($"\t\tentity.Update({argsCall});");
                    sb.AppendLine();
                    sb.AppendLine("\t\treturn Result.Success();");
                    sb.AppendLine("\t}");
                    sb.AppendLine();
                }

                sb.AppendLine($"\tpublic Result {deleteName}({c.ElementIdType} id)");
                sb.AppendLine("\t{");
                sb.AppendLine($"\t\tvar entity = {c.BackingFieldName}.FirstOrDefault(a => a.Id == id);");
                sb.AppendLine("\t\tif (entity is null)");
                sb.AppendLine(
                    $"\t\t\treturn Result.Failure(new Error(\"{ClassName}.{c.PropertyName}\", \"Not found\"));");
                sb.AppendLine();
                sb.AppendLine($"\t\t{c.BackingFieldName}.Remove(entity);");
                sb.AppendLine();
                sb.AppendLine("\t\treturn Result.Success();");
                sb.AppendLine("\t}");
            }
            else
            {
                // Owner ma [NoResultPattern] => metody kolekcji bez Result
                sb.AppendLine($"\tpublic {c.ElementType}? {addName}({argsDecl})");
                sb.AppendLine("\t{");
                sb.AppendLine($"\t\tvar entity = {c.ElementType}.Create({argsCall});");
                sb.AppendLine("\t\tif (entity is null)");
                sb.AppendLine("\t\t\treturn null;");
                sb.AppendLine();
                sb.AppendLine($"\t\t{c.BackingFieldName}.Add(entity);");
                sb.AppendLine();
                sb.AppendLine("\t\treturn entity;");
                sb.AppendLine("\t}");
                sb.AppendLine();

                sb.AppendLine($"\tpublic void {updateName}({c.ElementIdType} id, {argsDecl})");
                sb.AppendLine("\t{");
                sb.AppendLine($"\t\tvar entity = {c.BackingFieldName}.FirstOrDefault(a => a.Id == id);");
                sb.AppendLine("\t\tif (entity is null)");
                sb.AppendLine("\t\t\treturn;");
                sb.AppendLine();
                sb.AppendLine($"\t\tentity.Update({argsCall});");
                sb.AppendLine("\t}");
                sb.AppendLine();

                sb.AppendLine($"\tpublic void {deleteName}({c.ElementIdType} id)");
                sb.AppendLine("\t{");
                sb.AppendLine($"\t\tvar entity = {c.BackingFieldName}.FirstOrDefault(a => a.Id == id);");
                sb.AppendLine("\t\tif (entity is null)");
                sb.AppendLine("\t\t\treturn;");
                sb.AppendLine();
                sb.AppendLine($"\t\t{c.BackingFieldName}.Remove(entity);");
                sb.AppendLine("\t}");
            }
        }

        return sb.ToString();
    }

    protected override bool IsEmpty() =>
        Usings.Length == 0 &&
        Namespace.Length == 0 &&
        ClassName.Length == 0;
}