using System.Linq;
using DomainSmith.Abstraction.Common;
using DomainSmith.Abstraction.Common.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DomainSmith.Abstraction.Extensions;

public static class PropertyDeclarationSyntaxExtensions
{
    public static PropertyInfo ToPropertyInfo(this PropertyDeclarationSyntax propertySyntax,
        GeneratorSyntaxContext context)
    {
        var symbol = context.SemanticModel.GetDeclaredSymbol(propertySyntax);
        var isAutoGenerated = symbol?.GetAttributes().Any(a =>
            a.AttributeClass?.ToDisplayString() == typeof(AutoGeneratedAttribute).FullName!) == true;

        return new PropertyInfo(
            propertySyntax.Type.ToString(),
            propertySyntax.Identifier.Text,
            isAutoGenerated
        );
    }

    public static bool IsExcludedFromGeneration(this PropertyDeclarationSyntax propertySyntax,
        GeneratorSyntaxContext context)
    {
        var symbol = context.SemanticModel.GetDeclaredSymbol(propertySyntax);
        if (symbol is null) return true;

        return symbol.GetAttributes()
            .Any(a => a.AttributeClass?.ToDisplayString() == typeof(ExcludeFromGenerationAttribute).FullName!);
    }
}