using DomainSmith.AggregateRoot.Generators;
using DomainSmith.Tests.Helpers.Creators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace DomainSmith.AggregateRoot.Tests.Generators;

public sealed class AggregateRootGeneratorTests
{
    #region Properties

    [Fact]
    public async Task AggregateRootGenerator_WithStringProperty_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithStringProperty);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }


    private const string InputSourceWithStringProperty =
        """
        using DomainSmith.AggregateRoot;

        namespace TestNamespace;

        [AggregateRoot(typeof(Guid))]
        public sealed partial class TestAggregateRoot
        {
            public string Name { get; private set; }
        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithExcludedStringProperty_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithExcludedStringProperty);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }


    private const string InputSourceWithExcludedStringProperty =
        """
        using DomainSmith.AggregateRoot;
        using DomainSmith.Abstraction.Common;

        namespace TestNamespace;

        [AggregateRoot(typeof(Guid))]
        public sealed partial class TestAggregateRoot
        {
            [ExcludeFromGeneration] public string Name { get; private set; }
            
            public string Name2 { get; private set; }
        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithAutoGeneratedDateTimeProperty_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithAutoGeneratedDateTimeProperty);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());
        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();
        // Assert
        await Verify(output);
    }


    private const string InputSourceWithAutoGeneratedDateTimeProperty =
        """
        using DomainSmith.AggregateRoot;
        using DomainSmith.Abstraction.Common;

        namespace TestNamespace;

        [AggregateRoot(typeof(Guid))]
        public sealed partial class TestAggregateRoot
        {
            [AutoGenerated] public DateTime CreatedAt { get; private set; }
            
            public string Name { get; private set; }

        }
        """;


    [Fact]
    public async Task AggregateRootGenerator_WithIntProperty_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithIntProperty);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }


    private const string InputSourceWithIntProperty =
        """
        using DomainSmith.AggregateRoot;

        namespace TestNamespace;

        [AggregateRoot(typeof(Guid))]
        public sealed partial class TestAggregateRoot
        {
            public int Counter { get; private set; }
        }
        """;

    #endregion

    #region AggregateRootId

    [Fact]
    public async Task AggregateRootGenerator_WithShortId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithShortId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }

    private const string InputSourceWithShortId =
        """
        using DomainSmith.AggregateRoot;

        namespace TestNamespace;

        [AggregateRoot(typeof(short))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;


    [Fact]
    public async Task AggregateRootGenerator_WithValueShortId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithValueShortId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }

    private const string InputSourceWithValueShortId =
        """
        using DomainSmith.AggregateRoot;
        using DomainSmith.Abstraction.Core.Primitives;

        namespace TestNamespace;

        public sealed record TestAggregateRootId(short Value) : AggregateRootIdRecord<short>(Value);

        [AggregateRoot(typeof(TestAggregateRootId))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithUShortId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithUShortId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }


    private const string InputSourceWithUShortId =
        """
        using DomainSmith.AggregateRoot;

        namespace TestNamespace;

        [AggregateRoot(typeof(ushort))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithValueUShortId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithValueUShortId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }

    private const string InputSourceWithValueUShortId =
        """
        using DomainSmith.AggregateRoot;
        using DomainSmith.Abstraction.Core.Primitives;

        namespace TestNamespace;

        public sealed record TestAggregateRootId(ushort Value) : AggregateRootIdRecord<ushort>(Value);

        [AggregateRoot(typeof(TestAggregateRootId))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithIntId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithIntId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }


    private const string InputSourceWithIntId =
        """
        using DomainSmith.AggregateRoot;

        namespace TestNamespace;

        [AggregateRoot(typeof(int))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithValueIntId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithValueIntId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }

    private const string InputSourceWithValueIntId =
        """
        using DomainSmith.AggregateRoot;
        using DomainSmith.Abstraction.Core.Primitives;

        namespace TestNamespace;

        public sealed record TestAggregateRootId(int Value) : AggregateRootIdRecord<int>(Value);

        [AggregateRoot(typeof(TestAggregateRootId))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithUIntId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithUIntId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }


    private const string InputSourceWithUIntId =
        """
        using DomainSmith.AggregateRoot;

        namespace TestNamespace;

        [AggregateRoot(typeof(uint))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithValueUIntId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithValueUIntId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }

    private const string InputSourceWithValueUIntId =
        """
        using DomainSmith.AggregateRoot;
        using DomainSmith.Abstraction.Core.Primitives;

        namespace TestNamespace;

        public sealed record TestAggregateRootId(uint Value) : AggregateRootIdRecord<uint>(Value);

        [AggregateRoot(typeof(TestAggregateRootId))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithLongId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithLongId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }

    private const string InputSourceWithLongId =
        """
        using DomainSmith.AggregateRoot;

        namespace TestNamespace;

        [AggregateRoot(typeof(long))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;


    [Fact]
    public async Task AggregateRootGenerator_WithValueLongId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithValueLongId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }

    private const string InputSourceWithValueLongId =
        """
        using DomainSmith.AggregateRoot;
        using DomainSmith.Abstraction.Core.Primitives;

        namespace TestNamespace;

        public sealed record TestAggregateRootId(long Value) : AggregateRootIdRecord<long>(Value);

        [AggregateRoot(typeof(TestAggregateRootId))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithULongId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithULongId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }


    private const string InputSourceWithULongId =
        """
        using DomainSmith.AggregateRoot;

        namespace TestNamespace;

        [AggregateRoot(typeof(ulong))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithValueULongId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithValueULongId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }

    private const string InputSourceWithValueULongId =
        """
        using DomainSmith.AggregateRoot;
        using DomainSmith.Abstraction.Core.Primitives;

        namespace TestNamespace;

        public sealed record TestAggregateRootId(ulong Value) : AggregateRootIdRecord<ulong>(Value);

        [AggregateRoot(typeof(TestAggregateRootId))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithInt128Id_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithInt128Id);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }


    private const string InputSourceWithInt128Id =
        """
        using DomainSmith.AggregateRoot;

        namespace TestNamespace;

        [AggregateRoot(typeof(Int128))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithValueInt128Id_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithValueInt128Id);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }

    private const string InputSourceWithValueInt128Id =
        """
        using DomainSmith.AggregateRoot;
        using DomainSmith.Abstraction.Core.Primitives;

        namespace TestNamespace;

        public sealed record TestAggregateRootId(Int128 Value) : AggregateRootIdRecord<Int128>(Value);

        [AggregateRoot(typeof(TestAggregateRootId))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithUInt128Id_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithUInt128Id);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }


    private const string InputSourceWithUInt128Id =
        """
        using DomainSmith.AggregateRoot;

        namespace TestNamespace;

        [AggregateRoot(typeof(UInt128))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithValueUInt128Id_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithValueUInt128Id);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }

    private const string InputSourceWithValueUInt128Id =
        """
        using DomainSmith.AggregateRoot;
        using DomainSmith.Abstraction.Core.Primitives;

        namespace TestNamespace;

        public sealed record TestAggregateRootId(UInt128 Value) : AggregateRootIdRecord<UInt128>(Value);

        [AggregateRoot(typeof(TestAggregateRootId))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithGuidId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithGuidId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }


    private const string InputSourceWithGuidId =
        """
        using DomainSmith.AggregateRoot;

        namespace TestNamespace;

        [AggregateRoot(typeof(Guid))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithValueGuidId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithValueGuidId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }

    private const string InputSourceWithValueGuidId =
        """
        using DomainSmith.AggregateRoot;
        using DomainSmith.Abstraction.Core.Primitives;

        namespace TestNamespace;

        public sealed record TestAggregateRootId(Guid Value) : AggregateRootIdRecord<Guid>(Value);

        [AggregateRoot(typeof(TestAggregateRootId))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithStringId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithStringId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }

    private const string InputSourceWithStringId =
        """
        using DomainSmith.AggregateRoot;

        namespace TestNamespace;

        [AggregateRoot(typeof(string))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithValueStringId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithValueStringId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }

    private const string InputSourceWithValueStringId =
        """
        using DomainSmith.AggregateRoot;
        using DomainSmith.Abstraction.Core.Primitives;

        namespace TestNamespace;

        public sealed record TestAggregateRootId(string Value) : AggregateRootIdRecord<string>(Value);

        [AggregateRoot(typeof(TestAggregateRootId))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    [Fact]
    public async Task AggregateRootGenerator_WithClassValueStringId_ShouldGenerateCode()
    {
        // Arrange
        var inputCompilation = CompilationCreator.CreateCompilation(InputSourceWithClassValueStringId);
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new AggregateRootGenerator());

        // Act
        driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out _);
        var output = outputCompilation.SyntaxTrees.Last().ToString();

        // Assert
        await Verify(output);
    }

    private const string InputSourceWithClassValueStringId =
        """
        using DomainSmith.AggregateRoot;
        using DomainSmith.Abstraction.Core.Primitives;

        namespace TestNamespace;

        public sealed record TestAggregateRootId(string value) : AggregateRootIdClass<string>(value);

        [AggregateRoot(typeof(TestAggregateRootId))]
        public sealed partial class TestAggregateRoot
        {

        }
        """;

    #endregion
}