using System.Reflection;
using DomainSmith.AggregateRoot.Generators;
using FluentAssertions;

namespace DomainSmith.AggregateRoot.Tests.Generators;

public sealed class AggregateRootBuilderTests
{
    private static object CreatePropertyInfo(string type, string name, bool autoGenerated)
    {
        var nested =
            typeof(AggregateRootGenerator).GetNestedType("PropertyInfo", BindingFlags.Public | BindingFlags.NonPublic);
        nested.Should().NotBeNull("PropertyInfo nested type must exist");

        var instance = Activator.CreateInstance(
            nested,
            BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic,
            binder: null,
            args: [type, name, autoGenerated],
            culture: null);

        instance.Should().NotBeNull("PropertyInfo instance should be creatable via reflection");
        return instance;
    }

    [Fact]
    public void Build_WithTwoProperties_ShouldGenerateClassWithCtorCreateUpdateHooks()
    {
        // Arrange
        var builder = new AggregateRootBuilder();
        builder.SetUsings(["using System;"]);
        builder.SetNamespace("TestNamespace");
        builder.SetClassName("Cart");
        builder.SetTypeAgr("Guid");
        builder.SetIdValue("Guid.NewGuid()");
        builder.SetProperties([
            (AggregateRootGenerator.PropertyInfo)CreatePropertyInfo("string", "Title", false),
            (AggregateRootGenerator.PropertyInfo)CreatePropertyInfo("int", "ItemsCount", false)
        ]);

        // Act
        var output = builder.Build();

        // Assert
        output.Should().NotBeNullOrWhiteSpace();
        output.Should().Contain("// <auto-generated/>");
        output.Should().Contain("namespace TestNamespace;");
        output.Should().Contain("partial class Cart : AggregateRoot<Guid>");
        output.Should().Contain("private Cart(Guid id, string title, int itemscount) : base(id)");
        output.Should().Contain("Title = title;");
        output.Should().Contain("ItemsCount = itemscount;");
        output.Should().Contain("public static Cart? Create(string title, int itemscount)");
        output.Should().Contain("bool canCreate = true;");
        output.Should().Contain("OnCreatingAuto(ref title, ref itemscount, ref canCreate);");
        output.Should().Contain("OnCreating(ref title, ref itemscount, ref canCreate);");
        output.Should().Contain("var result = new Cart(Guid.NewGuid(), title, itemscount);");
        output.Should().Contain("OnCreated(result, ref canCreate);");
        output.Should().Contain("if(!canCreate) return null;");
        output.Should().Contain("return result;");
        output.Should().Contain("public void Update(string title, int itemscount)");
        output.Should().Contain("bool canUpdate = true;");
        output.Should().Contain("OnUpdatingAuto(ref title, ref itemscount, ref canUpdate);");
        output.Should().Contain("OnUpdating(ref title, ref itemscount, ref canUpdate);");
        output.Should().Contain("var tmpTitle = Title;");
        output.Should().Contain("var tmpItemsCount = ItemsCount;");
        output.Should().Contain("Title = title;");
        output.Should().Contain("ItemsCount = itemscount;");
        output.Should().Contain("OnUpdated(ref canUpdate);");
        output.Should().Contain("if(!canUpdate)");
        output.Should().Contain("Title = tmpTitle;");
        output.Should().Contain("ItemsCount = tmpItemsCount;");
        output.Should().Contain("static partial void OnCreatingTitle(ref string title, ref bool canCreate);");
        output.Should().Contain("static partial void OnCreatingItemsCount(ref int itemscount, ref bool canCreate);");
        output.Should().Contain("partial void OnUpdatingTitle(ref string title, ref bool canUpdate);");
        output.Should().Contain("partial void OnUpdatingItemsCount(ref int itemscount, ref bool canUpdate);");
        output.Should().Contain("OnCreatingTitle(ref title, ref canCreate);");
        output.Should().Contain("OnCreatingItemsCount(ref itemscount, ref canCreate);");
        output.Should().Contain("OnUpdatingTitle(ref title, ref canUpdate);");
        output.Should().Contain("OnUpdatingItemsCount(ref itemscount, ref canUpdate);");

        builder.Clear();
    }

    [Fact]
    public void Build_WithAutoGeneratedProperty_ShouldIncludeCreateAndUpdateAutoMethodsCalls()
    {
        // Arrange
        var builder = new AggregateRootBuilder();
        builder.SetUsings(["using System;"]);
        builder.SetNamespace("AutoNamespace");
        builder.SetClassName("Order");
        builder.SetTypeAgr("int");
        builder.SetIdValue("0");
        builder.SetProperties([
            (AggregateRootGenerator.PropertyInfo)CreatePropertyInfo("decimal", "Total", false),
            (AggregateRootGenerator.PropertyInfo)CreatePropertyInfo("DateTime", "CreatedAt", true)
        ]);

        // Act
        var output = builder.Build();

        // Assert
        output.Should().NotBeNullOrWhiteSpace();
        output.Should().Contain("namespace AutoNamespace;");
        output.Should().Contain("partial class Order : AggregateRoot<int>");
        output.Should().Contain("private Order(int id, decimal total) : base(id)");
        output.Should().Contain("Total = total;");
        output.Should().Contain("public static Order? Create(decimal total)");
        output.Should().Contain("var result = new Order(0, total);");
        output.Should().Contain("result.CreateCreatedAt();");
        output.Should().Contain("partial void CreateCreatedAt();");
        output.Should().Contain("public void Update(decimal total)");
        output.Should().Contain("UpdateCreatedAt();");
        output.Should().Contain("partial void UpdateCreatedAt();");

        builder.Clear();
    }

    [Fact]
    public void Build_WithMissingInputs_ShouldReturnEmptyString()
    {
        // Arrange
        var builder = new AggregateRootBuilder();

        // Act
        var output = builder.Build();

        // Assert
        output.Should().BeEmpty();
    }
}