namespace DomainSmith.Abstraction.Common.Models;

public sealed class PropertyInfo(string type, string name, bool autoGenerated)
{
    public string Type { get; } = type;
    public string Name { get; } = name;
    public bool AutoGenerated { get; set; } = autoGenerated;
}