using DomainSmith.Abstraction.Common;
using DomainSmith.Abstraction.Core.Primitives;
using DomainSmith.Entity;

namespace DomainSmith.AggregateRoot.Examples.AggregateRoots;

public record OwnerId(Guid Value) : EntityIdRecord<Guid>(Value);

public record Address(string Street, string City, string State, string ZipCode);

public record CarId(Guid Value) : EntityIdRecord<Guid>(Value);

[Entity(typeof(CarId))]
public partial class Car
{
    public string Name { get; private set; }
    public string Type { get; private set; }
    public decimal Price { get; private set; }
}

[AggregateRoot(typeof(OwnerId))]
public partial class Owner
{
    private readonly HashSet<Car> _newCars = [];
    private readonly HashSet<Car> _oldCars = [];

    public string FirstName { get; private set; }
    public string LastName { get; private set; }
    public string Email { get; private set; }
    public Address? Address { get; private set; }
    [ExcludeFromGeneration] public bool IsEnabled { get; private set; }
    [AutoGenerated] public DateTime? ModifiedAt { get; private set; }
    [AutoGenerated] public DateTime CreatedAt { get; private set; }
}