using DomainSmith.Abstraction.Common;
using DomainSmith.Abstraction.Core.Primitives;
using DomainSmith.Entity;

namespace DomainSmith.AggregateRoot.Examples.AggregateRoots;

public record OwnerId(Guid Value) : EntityIdRecord<Guid>(Value);

public record Address(string Street, string City, string State, string ZipCode);

public record CarId(Guid Value) : EntityIdRecord<Guid>(Value);

[Entity(typeof(CarId))]
public partial class Car
{
    public string Name { get; private set; }
    public string Type { get; private set; }
    public decimal Price { get; private set; }
}

[AggregateRoot(typeof(OwnerId))]
public partial class Owner
{
    private readonly HashSet<Car> _cars = [];

    public string FirstName { get; private set; }
    public string LastName { get; private set; }
    public string Email { get; private set; }
    public Address? Address { get; private set; }
    [ExcludeFromGeneration] public bool IsEnabled { get; private set; }
    [AutoGenerated] public DateTime? ModifiedAt { get; private set; }
    [AutoGenerated] public DateTime CreatedAt { get; private set; }

    ////Generate
    //[ExcludeFromGeneration] public IReadOnlyCollection<Car> Cars => _cars;

    ////Generate
    //public Result<Car> AddCar(string name, string type, decimal price)
    //{
    //    var result = Car.Create(name, type, price);

    //    if (result.IsFailure)
    //        return result;

    //    var car = result.Value();

    //    _cars.Add(car);

    //    return car;
    //}

    ////Generate
    //public Result UpdateCar(CarId id, string name, string type, decimal price)
    //{
    //    var car = _cars.FirstOrDefault(a => a.Id == id);
    //    if (car is null)
    //        return Result.Failure(new Error("Owner.Cars", "Not found"));

    //    var result = car.Update(name, type, price);

    //    return result;
    //}

    ////Generate
    //public Result DeleteCar(CarId id)
    //{
    //    var car = _cars.FirstOrDefault(a => a.Id == id);
    //    if (car is null)
    //        return Result.Failure(new Error("Owner.Cars", "Not found"));

    //    _cars.Remove(car);

    //    return Result.Success();
    //}
}