using DomainSmith.Abstraction.Generators;
using System.Text;

namespace DomainSmith.Entity.Generators;

internal sealed class EntityBuilder : BaseBuilder
{
    private readonly StringBuilder _typeAgr = new();
    private readonly StringBuilder _idValue = new();
    private readonly StringBuilder _extensionName = new();
    private List<(string Type, string Name, bool AutoGenerated)> _properties = [];

    internal void SetTypeAgr(string typeAgr)
    {
        _typeAgr.Clear();
        _typeAgr.Append(typeAgr);
    }

    internal void SetIdValue(string idValue)
    {
        _idValue.Clear();
        _idValue.Append(idValue);
    }

    internal void SetExtensionName(string className)
    {
        _extensionName.Clear();
        _extensionName.Append(className);
        _extensionName.Append("Extensions");
    }

    internal void SetProperties(List<EntityGenerator.PropertyInfo> properties)
    {
        _properties = [.. properties.Select(p => (p.Type, p.Name, p.AutoGenerated))];
    }


    protected override string BuildSource()
    {
        var resultStr = $"result";
        var ctorParams = new List<string> { $"{_typeAgr} id" };
        var ctorAssignments = new List<string>();
        var createParams = new List<string>();
        var createArgs = new List<string> { _idValue.ToString() };
        var onCreatingParams = new List<string>();
        var onUpdatingParams = new List<string>();
        var onCreatingRefParams = new List<string>();
        var onUpdatingRefParams = new List<string>();
        var updateAssignments = new List<string>();
        var updateTmpVars = new List<string>();
        var updateRestore = new List<string>();
        var createAutoGeneratedProps = new List<string>();
        var createAutoGeneratedMethods = new List<string>();
        var updateAutoGeneratedProps = new List<string>();
        var updateAutoGeneratedMethods = new List<string>();

        var perCreateDecls = new List<string>();
        var perUpdateDecls = new List<string>();
        var perCreateInvocations = new List<string>();
        var perUpdateInvocations = new List<string>();

        foreach (var (type, name, autoGenerated) in _properties)
        {
            if (autoGenerated)
            {
                createAutoGeneratedProps.Add($"{resultStr}.Create{name}();");
                updateAutoGeneratedProps.Add($"Update{name}();");

                createAutoGeneratedMethods.Add($"partial void Create{name}();");
                updateAutoGeneratedMethods.Add($"partial void Update{name}();");

                continue;
            }

            ctorParams.Add($"{type} {name.ToLower()}");
            ctorAssignments.Add($"{name} = {name.ToLower()};");
            createParams.Add($"{type} {name.ToLower()}");
            createArgs.Add($"{name.ToLower()}");
            onCreatingParams.Add($"ref {type} {name.ToLower()}");
            onUpdatingParams.Add($"ref {type} {name.ToLower()}");
            onCreatingRefParams.Add($"ref {name.ToLower()}");
            onUpdatingRefParams.Add($"ref {name.ToLower()}");
            updateTmpVars.Add($"var tmp{name} = {name};");
            updateAssignments.Add($"{name} = {name.ToLower()};");
            updateRestore.Add($"{name} = tmp{name};");

            perCreateDecls.Add($"static partial void OnCreating{name}(ref {type} {name.ToLower()}, ref bool canCreate);");
            perUpdateDecls.Add($"partial void OnUpdating{name}(ref {type} {name.ToLower()}, ref bool canUpdate);");

            perCreateInvocations.Add($"OnCreating{name}(ref {name.ToLower()}, ref canCreate);");
            perUpdateInvocations.Add($"OnUpdating{name}(ref {name.ToLower()}, ref canUpdate);");
        }

        var ctorParamsStr = string.Join(", ", ctorParams);
        var ctorAssignmentsStr = string.Join("\n\t\t", ctorAssignments);
        var createParamsStr = string.Join(", ", createParams);
        var createArgsStr = string.Join(", ", createArgs);
        var onCreatingParamsStr = string.Join(", ", onCreatingParams);
        var onUpdatingParamsStr = string.Join(", ", onUpdatingParams);
        var onCreatingRefParamsStr = string.Join(", ", onCreatingRefParams);
        var onUpdatingRefParamsStr = string.Join(", ", onUpdatingRefParams);
        var updateTmpVarsStr = string.Join("\n\t\t", updateTmpVars);
        var updateAssignmentsStr = string.Join("\n\t\t", updateAssignments);
        var updateRestoreStr = string.Join("\n\t\t\t", updateRestore);
        var createAutoGeneratedPropsStr = string.Join("\n\t\t", createAutoGeneratedProps);
        var createAutoGeneratedMethodsStr = string.Join("\n\t", createAutoGeneratedMethods);
        var updateAutoGeneratedPropsStr = string.Join("\n\t\t", updateAutoGeneratedProps);
        var updateAutoGeneratedMethodsStr = string.Join("\n\t", updateAutoGeneratedMethods);

        var perCreateDeclsStr = string.Join("\n\t", perCreateDecls);
        var perUpdateDeclsStr = string.Join("\n\t", perUpdateDecls);
        var perCreateInvocationsStr = string.Join("\n\t\t", perCreateInvocations);
        var perUpdateInvocationsStr = string.Join("\n\t\t", perUpdateInvocations);

        return $$"""
                 // <auto-generated/>
                 {{Usings}}

                 {{Namespace}}

                 partial class {{ClassName}} : Entity<{{_typeAgr}}>
                 {
                     private {{ClassName}}({{ctorParamsStr}}) : base(id)
                     {
                         {{ctorAssignmentsStr}}
                     }

                     internal static {{ClassName}}? Create({{createParamsStr}})
                     {
                         bool canCreate = true;
                         OnCreatingAuto({{onCreatingRefParamsStr}}, ref canCreate);
                         OnCreating({{onCreatingRefParamsStr}}, ref canCreate);
                     
                         var {{resultStr}} = new {{ClassName}}({{createArgsStr}});
                                                  
                         OnCreated(result, ref canCreate);
                         if(!canCreate) return null;

                         {{createAutoGeneratedPropsStr}}

                         return {{resultStr}};
                     }
                     
                     internal void Update({{createParamsStr}})
                     {
                         bool canUpdate = true;
                         OnUpdatingAuto({{onUpdatingRefParamsStr}}, ref canUpdate);
                         OnUpdating({{onUpdatingRefParamsStr}}, ref canUpdate);
                         
                         {{updateTmpVarsStr}}
                         {{updateAssignmentsStr}}
                         
                         OnUpdated(ref canUpdate);
                         if(!canUpdate)
                         {
                            {{updateRestoreStr}}
                            return;
                         }
                         {{updateAutoGeneratedPropsStr}}
                     
                         return;
                     }

                     private static void OnCreatingAuto({{onCreatingParamsStr}}, ref bool canCreate)
                     {
                         {{perCreateInvocationsStr}}
                     }

                     private void OnUpdatingAuto({{onUpdatingParamsStr}}, ref bool canUpdate)
                     {
                         {{perUpdateInvocationsStr}}
                     }
                     
                     static partial void OnCreating({{onCreatingParamsStr}}, ref bool canCreate);
                     static partial void OnCreated({{ClassName}} result, ref bool canCreate);

                     partial void OnUpdating({{onUpdatingParamsStr}}, ref bool canUpdate);
                     partial void OnUpdated(ref bool canUpdate);

                     {{createAutoGeneratedMethodsStr}}
                     {{updateAutoGeneratedMethodsStr}}

                     {{perCreateDeclsStr}}
                     {{perUpdateDeclsStr}}
                 }                 
                 """;
    }

    protected override bool IsEmpty() =>
        Usings.Length == 0 &&
        Namespace.Length == 0 &&
        ClassName.Length == 0;
}