using DomainSmith.Abstraction.Generators;
using System.Text;

namespace DomainSmith.ValueObject.Generators;

internal sealed class ValueObjectBuilder : BaseBuilder
{
    private readonly StringBuilder _extensionName = new();
    private readonly StringBuilder _extensionReference = new();
    private List<(string Type, string Name)> _properties = [];
    private bool _isResultPattern = true;

    internal void SetExtensionName(string className)
    {
        _extensionName.Clear();
        _extensionName.Append(className);
        _extensionName.Append("Extensions");
    }

    internal void SetExtensionReference(string? @namespace, string className)
    {
        _extensionReference.Clear();

        if (!string.IsNullOrEmpty(@namespace))
        {
            _extensionReference.Append(@namespace);
            _extensionReference.Append(".");
        }

        _extensionReference.Append(className);
        _extensionReference.Append("Extensions");
    }

    internal void SetProperties(List<(string Type, string Name)> properties)
    {
        _properties = [.. properties];
    }

    internal void SetIsResultPattern(bool isResultPattern)
    {
        _isResultPattern = isResultPattern;
    }

    protected override string BuildSource()
    {
        var ctorParams = new List<string>();
        var ctorAssignments = new List<string>();
        var createParams = new List<string>();
        var createArgs = new List<string>();
        var onCreatingRefParams = new List<string>();
        var onCreatingParams = new List<string>();

        foreach (var (type, name) in _properties)
        {
            var paramName = name.ToLower();
            ctorParams.Add($"{type} {paramName}");
            ctorAssignments.Add($"{name} = {paramName};");
            createParams.Add($"{type} {paramName}");
            createArgs.Add($"{paramName}");
            onCreatingRefParams.Add($"ref {paramName}");
            onCreatingParams.Add($"ref {type} {paramName}");
        }

        var ctorParamsStr = string.Join(", ", ctorParams);
        var ctorAssignmentsStr = string.Join("\n\t\t", ctorAssignments);
        var createParamsStr = string.Join(", ", createParams);
        var createArgsStr = string.Join(", ", createArgs);
        var onCreatingRefParamsStr = string.Join(", ", onCreatingRefParams);
        var onCreatingParamsStr = string.Join(", ", onCreatingParams);

        var createResult = _isResultPattern ? $"Result<{ClassName}>" : $"{ClassName}?";
        var createReturn = _isResultPattern ? "return Result.Success(result);" : "return result;";
        var createFailReturn = _isResultPattern
            ? "return Result.Failure<" + ClassName + ">(error);"
            : "return null;";
        var refDeclParams = _isResultPattern ? "ref bool canCreate, ref Error error" : "ref bool canCreate";
        var refParams = _isResultPattern ? "ref canCreate, ref error" : "ref canCreate";
        var refVars = _isResultPattern
            ? "bool canCreate = true;\n\t\tError error = Error.None;"
            : "bool canCreate = true;";

        if (_isResultPattern) Usings.Append("\nusing DomainSmith.Abstraction.Core.Result;");

        return $$"""
                 // <auto-generated/>
                 {{Usings}}

                 {{Namespace}}

                 partial record {{ClassName}}
                 {
                     private {{ClassName}}({{ctorParamsStr}})
                     {
                         {{ctorAssignmentsStr}}
                     }

                     public static {{createResult}} Create({{createParamsStr}})
                     {
                         {{refVars}}

                         OnCreating({{onCreatingRefParamsStr}}, {{refParams}});
                         
                         var result = new {{ClassName}}({{createArgsStr}});

                         OnCreated(result, {{refParams}});
                         if (!canCreate) {{createFailReturn}}

                         {{createReturn}}
                     }

                     static partial void OnCreating({{onCreatingParamsStr}}, {{refDeclParams}});
                     static partial void OnCreated({{ClassName}} instance, {{refDeclParams}});
                 }
                 """;
    }

    protected override bool IsEmpty()
    {
        return Usings.Length == 0 &&
               Namespace.Length == 0 &&
               ClassName.Length == 0;
    }
}