using DomainSmith.Abstraction.Generators;
using System.Text;

namespace DomainSmith.ValueObject.Generators;

internal sealed class ValueObjectBuilder : BaseBuilder
{
    private readonly StringBuilder _extensionName = new();
    private readonly StringBuilder _extensionReference = new();
    private List<(string Type, string Name)> _properties = [];
    internal void SetExtensionName(string className)
    {
        _extensionName.Clear();
        _extensionName.Append(className);
        _extensionName.Append("Extensions");
    }

    internal void SetExtensionReference(string? @namespace, string className)
    {
        _extensionReference.Clear();

        if (!string.IsNullOrEmpty(@namespace))
        {
            _extensionReference.Append(@namespace);
            _extensionReference.Append(".");
        }

        _extensionReference.Append(className);
        _extensionReference.Append("Extensions");
    }

    internal void SetProperties(List<(string Type, string Name)> properties)
    {
        _properties = [.. properties];
    }

    protected override string BuildSource()
    {
        var ctorParams = new List<string>();
        var ctorAssignments = new List<string>();
        var createParams = new List<string>();
        var createArgs = new List<string>();
        var onCreatingRefParams = new List<string>();
        var onCreatingParams = new List<string>();

        foreach (var (type, name) in _properties)
        {
            var paramName = name.ToLower();
            ctorParams.Add($"{type} {paramName}");
            ctorAssignments.Add($"{name} = {paramName};");
            createParams.Add($"{type} {paramName}");
            createArgs.Add($"{paramName}");
            onCreatingRefParams.Add($"ref {paramName}");
            onCreatingParams.Add($"ref {type} {paramName}");
        }

        var ctorParamsStr = string.Join(", ", ctorParams);
        var ctorAssignmentsStr = string.Join("\n\t\t", ctorAssignments);
        var createParamsStr = string.Join(", ", createParams);
        var createArgsStr = string.Join(", ", createArgs);
        var onCreatingRefParamsStr = string.Join(", ", onCreatingRefParams);
        var onCreatingParamsStr = string.Join(", ", onCreatingParams);

        return $$"""
                 // <auto-generated/>
                 {{Usings}}

                 {{Namespace}}

                 partial record {{ClassName}}
                 {
                     private {{ClassName}}({{ctorParamsStr}})
                     {
                         {{ctorAssignmentsStr}}
                     }

                     public static {{ClassName}}? Create({{createParamsStr}})
                     {
                         bool canCreate = true;

                         OnCreating({{onCreatingRefParamsStr}}, ref canCreate);
                         
                         var result = new {{ClassName}}({{createArgsStr}});

                         OnCreated(result, ref canCreate);
                         if (!canCreate) return null;

                         return result;
                     }

                     static partial void OnCreating({{onCreatingParamsStr}}, ref bool canCreate);
                     static partial void OnCreated({{ClassName}} instance, ref bool canCreate);
                 }
                 """;
    }

    protected override bool IsEmpty()
    {
        return Usings.Length == 0 &&
               Namespace.Length == 0 &&
               ClassName.Length == 0;
    }
}
